Add test
satorunooshie/swipe-shukatu pull request #41
Opened 2021-08-08 07:12 UTC by sivchari

2021-08-08 10:29 UTC, satorunooshie requested changes
LGTM

2021-08-08 10:29 UTC, satorunooshie commented on pkg/infrastructure/mysql/repoimpl/job_repoimpl_test.go
> +	t.Helper()
t.Helperいらなくね？

2021-08-08 11:48 UTC, sivchari commented on pkg/infrastructure/mysql/repoimpl/job_repoimpl_test.go
> +	t.Helper()
慣習的に全部のテストにつけるようにしてるんだよね

2021-08-08 13:33 UTC, satorunooshie reviewed
LTGM

2021-08-08 13:33 UTC, satorunooshie commented on pkg/interfaces/handler/message_handler_test.go
> +				t.Errorf("http.Get(%q) returned error %v", server.URL+"/"+strconv.Itoa(int(rID)), err)
[Q]
いまだにgofmtの文字列結合理解してない
なんで+の間に空白があるところとないところができるんだろう。。
[imo]
たくさん使うならブロックの中で定数で良さそう

2021-08-08 13:33 UTC, satorunooshie commented on pkg/interfaces/handler/message_handler_test.go
> +	"github.com/satorunooshie/swipe-shukatu/pkg/usecase/mock_usecase"
```suggestion
	"github.com/golang/mock/gomock"
	"github.com/google/go-cmp/cmp"

	"github.com/satorunooshie/swipe-shukatu/pkg/usecase"
	"github.com/satorunooshie/swipe-shukatu/pkg/usecase/mock_usecase"
```

2021-08-08 15:39 UTC, sivchari commented on pkg/interfaces/handler/message_handler_test.go
> +				t.Errorf("http.Get(%q) returned error %v", server.URL+"/"+strconv.Itoa(int(rID)), err)
定数どこをいってる？

2021-08-08 15:39 UTC, sivchari commented on pkg/interfaces/handler/message_handler_test.go
> +				t.Errorf("http.Get(%q) returned error %v", server.URL+"/"+strconv.Itoa(int(rID)), err)
+は俺もわからん

2021-08-08 16:09 UTC, satorunooshie commented on pkg/interfaces/handler/message_handler_test.go
> +				t.Errorf("http.Get(%q) returned error %v", server.URL+"/"+strconv.Itoa(int(rID)), err)
ちゃりちゃりならわかると思ったのに！！！
```
const url = server.URL+"/"+strconv.Itoa(int(rID)
```
ここ！

2021-08-08 16:14 UTC, sivchari commented on pkg/interfaces/handler/message_handler_test.go
> +				t.Errorf("http.Get(%q) returned error %v", server.URL+"/"+strconv.Itoa(int(rID)), err)
むしろここ一回しか使ってないから定数化しなくていいと思ったけど

2021-08-08 16:27 UTC, satorunooshie reviewed
https://github.com/satorunooshie/swipe-shukatu/pull/41#discussion_r684797146

2021-08-08 16:27 UTC, satorunooshie commented on pkg/interfaces/handler/message_handler_test.go
> +				t.Errorf("http.Get(%q) returned status %v", server.URL+"/"+strconv.Itoa(int(rID)), res.Status)
こことか使ってるから、まあ良ければって感じ！

2021-08-08 16:27 UTC, satorunooshie commented on pkg/interfaces/handler/message_handler_test.go
> +			res, err := http.Get(server.URL + "/message/" + strconv.Itoa(int(rID)))
あとここ！

2021-08-09 08:47 UTC, joryulife approved these changes

2021-08-09 14:10 UTC, sivchari commented on pkg/interfaces/handler/message_handler_test.go
> +			res, err := http.Get(server.URL + "/message/" + strconv.Itoa(int(rID)))
任せるどうする？

2021-08-11 13:22 UTC, satorunooshie commented on pkg/interfaces/handler/message_handler_test.go
> +			res, err := http.Get(server.URL + "/message/" + strconv.Itoa(int(rID)))
このままでいいよー気づかなくて遅れちゃった

2021-08-11 17:35 UTC, satorunooshie commented
これmake genしなくていいんだっけ？

2021-08-12 03:08 UTC, satorunooshie commented
他のやつ(しぶちゃりの)は標準ライブラリ、サードパーティ、内部パッケージに分かれてるけど、コメントしたところは別れてないから気になった

2021-08-12 03:10 UTC, satorunooshie commented
手元でmake genしたらltd_repositoryあたり差分出たから、テスト書く前のPRでレビュー漏れてたけど必要だったかなって！

2021-08-12 03:56 UTC, sivchari commented
後で確認してpr更新する

2021-08-12 10:03 UTC, sivchari commented
@satorunooshie ping

2021-08-12 10:06 UTC, sivchari commented
conflictしてたからrebaseさせてもらった

2021-08-12 10:06 UTC, merged