バルクインサートとか考えないlikeの実装,mock,test未実装
satorunooshie/swipe-shukatu pull request #50
Opened 2021-08-13 09:56 UTC by joryulife

#13

2021-08-13 14:01 UTC, satorunooshie requested changes
いっぱいコメントしたわからなかったら聞いて&&意図があってコメント通り実装してないところがあったら言って！

2021-08-13 14:01 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +			body, err := ioutil.ReadAll(request.Body)
Body読むの先がいいね
```
var req request.LikePostRequest
json.NewDecoder(request.Body).Decode(&req)
```

みたいな感じが良さそう？

2021-08-13 14:05 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +		if method == "POST" {
そもpostをこっちにまわしてるからこのif methodがいらないのはそうです、、、

2021-08-13 14:09 UTC, joryulife commented on pkg/domain/model/like_model.go
> +	RecruitID int32 `json:"recruit_id"`
受け渡しにlike型にUIDいれて使ってるだけでクライアントとやりとりするjsonにuserIdは定義されてなかったので、、、

2021-08-13 14:13 UTC, joryulife commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +func (likeI *likeRepoImpl) Select(ctx context.Context) ([]*likeM.Like, error) {
ここUIDの取得方不明段階から放置してわすれてました、handlerで渡す時点で引数にUID渡しとくのがいいですね直します。

2021-08-13 14:13 UTC, joryulife commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +	stmt, err := likeI.db.Prepare("UPDATE like SET  WHERE ")
指摘修正感謝です。

2021-08-13 14:14 UTC, joryulife commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +	stmt, err := likeI.db.Prepare("INSERT INTO like VALUES ?")
mysql系統って全部の値いれるならテーブル名だけでいけませんでしたっけ？

2021-08-13 14:16 UTC, joryulife commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +func convertToLike(rows *sql.Rows) ([]*likeM.Like, error) {
メモ：select内のconvertToLikeも修正

2021-08-13 14:17 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +	mid "github.com/satorunooshie/swipe-shukatu/pkg/interfaces/middleware"
関数呼び出すだけだから名前つける意味ないですね
使ってるところ含め直します

2021-08-13 14:19 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +		ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
正直どこに何の検証おけばよいかわかってない、教えてください土下座

2021-08-13 14:20 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +				log.Fatal(err)
Fatalはos.exit呼びますよねごめんなさい気づいてませんでした。
InternalServerErrorに直す。

2021-08-13 14:22 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +			err = likeH.likeUseCase.Insert(ctx, like)
UIDを引数で渡してって認識でいいですか？

2021-08-13 14:25 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +				http.Error(writer, err.Error(), http.StatusInternalServerError)
上同文os.exi(ry
エラーハンドリングで軽々しくFatal使ってごめんなさい
log.Fatal(err)消します

2021-08-13 14:35 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +			}
if err == nil{
    writer.WriteHeader(http.StatusCreated)
}
でよい？

アーリーリターンでelse使ってるとネスト深くなりがちみたいな話はわかるけどGoの仕様でそうなってるのは知らなんだ
教えてくれてありがとう

2021-08-13 14:52 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +			body, err := ioutil.ReadAll(request.Body)
```
var like *likeM.Like
if err := json.NewDecoder(request.Body).Decode(&like); err != nil {
    http.Error
}
like.UID = UID
```

みたいな認識でいい？

ごめんどこを基点として先って話してる？=>Body読むの先がいいね

2021-08-13 14:56 UTC, satorunooshie commented on pkg/domain/model/like_model.go
> +	RecruitID int32 `json:"recruit_id"`
unexportなjsonタグはjson:"-"

2021-08-13 14:57 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +	mid "github.com/satorunooshie/swipe-shukatu/pkg/interfaces/middleware"
Goの思想で、import名指定するのは被った時か、わかりにくい時だけだった気がする

2021-08-13 14:59 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
Bodyのデコード
バリデーション
コンテキスト
DB
err check
レスポンス書き込み
の順かな？
全部必要になった時（必要な順）にすればいい！
どこにっていうのはパッケージ構成の話？

2021-08-13 15:03 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +			}
```suggestion
                         if err != nil {
				log.Fatal(err)
				http.Error(writer, err.Error(), http.StatusInternalServerError)
			        return
			} 
			writer.WriteHeader(http.StatusCreated)
```
こんな感じ

2021-08-13 15:03 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +			body, err := ioutil.ReadAll(request.Body)
何よりも先に！って意味だった！

2021-08-13 15:04 UTC, joryulife commented on pkg/domain/model/like_model.go
> +	RecruitID int32 `json:"recruit_id"`
無視して欲しい時のjsonタグは"-"でしたね、、、

2021-08-13 15:06 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +			}
```
retrun(
    ~
    if(){
        retrun
    }
)
```
でいいのか、、、ありがとうです

2021-08-13 15:08 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +			}
ref: https://golang.org/doc/effective_go#if

2021-08-13 16:39 UTC, sivchari requested changes

2021-08-13 16:39 UTC, sivchari commented on .vscode/settings.json
> +}
empty line

2021-08-13 16:39 UTC, sivchari commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +func (likeI *likeRepoImpl) Select(ctx context.Context) ([]*likeM.Like, error) {
selectcontext使って欲しい

2021-08-13 16:39 UTC, sivchari commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +	stmt, err := likeI.db.Prepare("INSERT INTO like VALUES ?")
preparecontext使って欲しい

2021-08-13 16:39 UTC, sivchari commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +	stmt, err := likeI.db.Prepare("UPDATE like SET  WHERE ")
ここも

2021-08-13 16:39 UTC, sivchari commented on pkg/interfaces/handler/like_handler.go
> +		if method == "POST" {
net/httpにpostのconstあったはず’

2021-08-13 16:42 UTC, satorunooshie commented
`http.MethodPost`

2021-08-13 19:05 UTC, satorunooshie commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +
```suggestion
// Select
```

2021-08-13 19:15 UTC, satorunooshie requested changes

2021-08-13 19:15 UTC, satorunooshie commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +func (likeI *likeRepoImpl) Select(ctx context.Context, UID string) ([]*likeM.Like, error) {
```suggestion
// Select
func (likeI *likeRepoImpl) Select(ctx context.Context, UID string) ([]*likeM.Like, error) {
```

2021-08-13 19:15 UTC, satorunooshie commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +			return nil, nil
ここnilで大丈夫そう？

2021-08-13 19:15 UTC, satorunooshie commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +	str := fmt.Sprintf("(%s,%d,%s,%s)", entity.UID, entity.RecruitID, t, t)
[nits]
```suggestion
	str := fmt.Sprintf("(%s, %d, %s, %s)", entity.UID, entity.RecruitID, t, t)
```

2021-08-13 19:15 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		lks := make([]*LikeResponse, len(lk))
41行目の時点でlikesでは？

2021-08-13 19:15 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		UID := dcontext.GetUIDFromContext(ctx)
```suggestion
		UID := dcontext.GetUIDFromContext(ctx)
		if UID == nil {
		
		}
```

2021-08-13 19:15 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		}
ここはloggingなし？

2021-08-13 19:15 UTC, satorunooshie commented on pkg/usecase/like_usecase.go
> +func (likeU *likeUseCase) Insert(ctx context.Context, entity *likeM.Like, UID string) error {
entityを引数で渡すと、ヒープ領域に入るから良くないし、それだったら最初から詰めてきた方がいいから、UIDだけ渡して、中で詰めるようにしよう

2021-08-13 19:16 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		lks := make([]*LikeResponse, len(lk))
46はresとかで良さそう
そうするとforの中は1文字変数でいいよ

2021-08-13 19:45 UTC, joryulife commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +			return nil, nil
検索結果0のerrHndleでnil返しすのは拙いか,,,
何入れとけばええんやろ

2021-08-13 20:06 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +		UID := dcontext.GetUIDFromContext(ctx)
UID stringだからnilと比較できない気がする
デフォルトってUID取得できなかった場合空文字列が返りますか？

2021-08-18 01:25 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
>  		if err := json.NewDecoder(request.Body).Decode(&like); err != nil {
ここ多分likeInsertRequestみたいなのにしないとDecodeしたやつ詰められないと思う

2021-08-19 10:08 UTC, joryulife commented
sql文を修正

2021-08-19 23:30 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		UID := dcontext.GetUIDFromContext(ctx)
空文字がかえる！

2021-08-19 23:30 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		UID := dcontext.GetUIDFromContext(ctx)
[nits]
[ERROR]じゃなくて[INFO]くらいで良さそう

2021-08-19 23:30 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +}
これは何に使ってる？

2021-08-19 23:30 UTC, satorunooshie commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +			return nil, nil
いやまあnilが意図した挙動なら問題ない
errはなしで返して、受け取った先でのnil判定があるなら！

2021-08-19 23:30 UTC, satorunooshie commented on pkg/interfaces/handler/like_handler.go
> +		if err := json.NewDecoder(request.Body).Decode(&like); err != nil {
これはRequest別定義の方がいい

2021-08-19 23:47 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +}
十中八九消し忘れ説

2021-08-19 23:49 UTC, joryulife commented on pkg/interfaces/handler/like_handler.go
> +		if err := json.NewDecoder(request.Body).Decode(&like); err != nil {
ごめん把握できてない

2021-08-20 01:04 UTC, satorunooshie commented on pkg/infrastructure/mysql/repoimpl/like_repoimpl.go
> +			&like.UpdateddAt,
```suggestion
			&like.UpdatedAt,
```

2021-08-20 01:07 UTC, satorunooshie commented on pkg/domain/model/like_model.go
> +	UpdateddAt time.Time `json:"updated_at"`
```suggestion
	UpdatedAt time.Time `json:"updated_at"`
```

2021-08-22 04:04 UTC, merged